version: "3.8"

services:
    mock_pl_dev_db:
        image: postgres:15-alpine
        env_file:
            - .env
        environment:
            - POSTGRES_USER=$DB_USERNAME
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - POSTGRES_DB=$DEV_DB
        # environment:
        #     POSTGRES_DB: pl_mock_db
        #     POSTGRES_USER: postgres
        #     POSTGRES_PASSWORD: temidayo
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432" # Expose PostgreSQL to the host machine (optional)

    redis:
        image: redis:latest
        command: ["redis-server", "--bind", "redis", "--port", "6379"]

    mock_pl_server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - mock_pl_dev_db
        env_file:
            - .env
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app # Mount the current directory for development purposes
        command: npm run dev

volumes:
    postgres-data:
